build: off

init:
  - git config --global core.autocrlf input

install:
  - cinst jdk8 -params 'installdir=C:\\jdk8'
  - cinst jdk9 -version 9.0.4.11 -params 'installdir=C:\\jdk9'
  - SET JAVA_HOME=C:\jdk8
  - SET PATH=C:\jdk8\bin;%PATH%

  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://cocl.us/sbt-0.13.16.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - SET PATH=C:\sbt\sbt\bin;%PATH%
  - SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g -Dfile.encoding=UTF8

test_script:
  - sbt "-Dsbt.build.version=1.0.4" universal:packageBin
  - cd citest
  - test.bat
  - test1.bat
  - test3/test3.bat
  - test4/test4.bat
